{% set name = "birdy" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: v{{ version }}

source:
  url: https://github.com/bird-house/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fe1be67a536d7c24f2710b8c2f0d7b5977e96c91cd50f9fe7a9cdc9979ca459d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - birdy = birdy.cli.run:cli

requirements:
  host:
    - python >=3
    - pip
    - setuptools
    - six
    - click
    - lxml
    - owslib >=0.18.0
    - jinja2
    - wrapt
    - funcsigs
    - boltons
  run:
    - python >=3
    - six
    - click
    - lxml
    - owslib >=0.18.0
    - jinja2
    - wrapt
    - funcsigs
    - boltons

test:
  imports:
    - birdy

about:
  home: http://github.com/bird-house/birdy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Birdy provides a command-line tool to work with Web Processing Services (WPS).

  description: |
    Birdy is a Python command-line tool to work with Web Processing Services (WPS).
    It is built with the capabilities of OWSLib from the GeoPython project and allows
    for ease in the development of WPS-enabled services as part of the Bird-house ecosystem.
  doc_url: https://birdy.readthedocs.io/en/stable/
  dev_url: http://github.com/bird-house/birdy

extra:
  recipe-maintainers:
    - cehbrecht
    - Zeitsperre
