{% set name = "birdy" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/birdhouse-birdy/birdhouse-birdy-{{ version }}.tar.gz
  sha256: 8414ec6fa39e7bba98f4345e338f38abbcbd74d5fec6a028bebc2a7677236f62

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - birdy = birdy.cli.run:cli

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - click
    - ipython
    - lxml
    - owslib >=0.21
    - jinja2
    - wrapt
    - funcsigs
    - boltons
    - python-dateutil >=2.8.1
    - requests >=2.0

test:
  imports:
    - birdy

about:
  home: http://github.com/bird-house/birdy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Birdy provides a command-line tool to work with Web Processing Services (WPS).

  description: |
    Birdy is a Python command-line tool to work with Web Processing Services (WPS).
    It is built with the capabilities of OWSLib from the GeoPython project and allows
    for ease in the development of WPS-enabled services as part of the Bird-house ecosystem.
  doc_url: https://birdy.readthedocs.io/en/stable/
  dev_url: http://github.com/bird-house/birdy

extra:
  recipe-maintainers:
    - cehbrecht
    - Zeitsperre
