travis:
  secure:
    BINSTAR_TOKEN: pMpufoiecm6pchvAhd5bTqpNZpZQClkhNwXCkDOFB+bt/43EqcZbCwPvEsgMa4pLLAjOpLswRcSZhtlkEpjPcnCnaDI+UG+xqExJaC++YsbUFMJXEveA5gS/iHX/yx4ONPy+h7wLQgWHR7aZTqmH77X3vCd/W767XRVJcu3zMe1AyKXLLigbLGVI+DDhuaquUeu2OFOplxCqJdz44GW18vL6j1IQsNPx+82HqftPzEsDK4XdfFJsTP0xxbTIh3w1OZpBpSoZStu+NWce7fe+0pphjETTOPdvItDOn99eiU+OugSC2+XjujOnJ8EUE7S98Ls4mtOlqgEDVAX5I0qYdgE0stP7v7YqIZahGbzoPQlpBA+OnVk2kc85priwY3r+7p31YzajI8k6pjt0CvZMP8VQBtmWLsoIDHsq5hl0Ls+DRgSWoLzwcPUkvTti7CbRegZvKTwkCI5FMprJWKB4IJmsjsH5yO9Z6xjInmsTc0n/j65SlXCep3CENKXA9Vz0WnLIo4UyXhu6p1ugO5YtXDj2EK9ZcASKubgRFNcq0mTfTSKJtdQsMEcoP6I2Tj2U/7v+c8DO2E706cc+tLpnnB/Mg3eumnbhbGeXmiHU8moUVorMX+an5DJ9Ihqkmsk05PhoCF3pLsSwDZCxlQ7KQqWB6xfiMzzkLE/SCtzBOj4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
