travis:
  secure:
    BINSTAR_TOKEN: eMAUVD2hzyrsDW1eeE3bZoZIM8+aKWO9sYPwzwD3Qe+z0SCShdGv27xT4zGmF4LW/zvEmWERx5CCQsu2pcCpqVApOYCfTg/bKVuIlbJLU+FHVmmjPHxou2CTl2MCV82lZf0YGNmgIN5gcpNMZ2J2lT5aLy+XM9Un++xZDMZau2joUfV5TmJEKpSSgtZC8y4852qPBzO87yNjvPp6ud5ShktuS6+/Fa9XPf2RI7jtkvwfLMpgZhrtHiRj5bCLlhzUdcAi2/YXk9inklc9eiIK09wJRF7PG1ILFL/OwVEqMiNDslaacn+yYWqNkgpEGyK3lIpDgJn6RomPcz5pL/4OZScASeEThW3voHXIESav4BIK/Udn/eav77dfbwo+h5sqGWp8P/DTieT5GO8YdW904nZEfzw/HI6OwtNk2JHtn8Unlry5V9k0M3inmp735dq6F3wx1iIFPEo70sG8QbfVW1Hh8JJ5BjkRQEr96p/0I6tPV77yMbEbX/xso4Etvtktsm/+yDyuT5FZfn0mb5mlQ2AEYavOiCiyaf7H3FJWxJsH5EjhzZVQttI9j01ufeRVDUgUx2YGYDFOJ4u4GLKCEpVUtPPraT6ydvPdzXG5/Q/fGvXUvsQ4xOYwkiKz0lQ7Cn9ohaHdTTxri2kBU/e2F/69ddjGTNpV9QfJvkkuoNQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
